# Generated by Django 4.2.4 on 2024-01-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(blank=True, max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('BirthDate', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('PresentAddress', models.TextField()),
                ('PermanentAddress', models.TextField()),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('PinCode', models.IntegerField()),
                ('Mobile', models.IntegerField()),
                ('EmergencyPhoneNo', models.IntegerField()),
                ('BloodGroup', models.CharField(max_length=10)),
                ('UserId', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('JoiningDate', models.DateField()),
                ('Qualification', models.CharField(max_length=100)),
                ('RefName', models.CharField(max_length=50)),
                ('RefMo', models.IntegerField()),
                ('UserName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('UploadDocument', models.FileField(blank=True, null=True, upload_to='user_documents/%d_%m_%Y/')),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
