# Generated by Django 4.2.4 on 2024-01-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0002_alter_userprofile_bloodgroup_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='BirthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
