# Generated by Django 4.2.4 on 2024-01-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0004_medicalform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medicalform',
        ),
    ]
