# Generated by Django 4.2.4 on 2024-01-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0005_delete_medicalform'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
