# Generated by Django 4.2.4 on 2024-01-12 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0008_alter_task_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='TaskAddedTime',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
