# Generated by Django 4.2.4 on 2024-01-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0009_task_taskaddedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='TaskAddedTime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
