# Generated by Django 4.2.4 on 2024-01-13 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0012_rename_checklist_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Addedby',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
