# Generated by Django 4.2.4 on 2024-01-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0013_task_addedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Attachments',
            field=models.FileField(blank=True, null=True, upload_to='Attachments/'),
        ),
    ]
