# Generated by Django 4.2.4 on 2024-01-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0014_alter_task_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Markasdone',
            field=models.BooleanField(default=False),
        ),
    ]
