# Generated by Django 4.2.4 on 2024-01-18 05:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0015_task_markasdone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.TimeField(default=datetime.datetime.now)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_by_id', to='officeapp.userprofile')),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_by_user', to='officeapp.userprofile')),
            ],
        ),
    ]
