# Generated by Django 4.2.4 on 2024-01-18 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0017_remove_checkinout_userid_remove_checkinout_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
