# Generated by Django 4.2.4 on 2024-01-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0018_alter_checkinout_check_in_alter_checkinout_check_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinout',
            name='user_profile',
        ),
    ]
