# Generated by Django 4.2.4 on 2024-01-18 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0019_remove_checkinout_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinout',
            name='user_profile',
            field=models.ForeignKey(default='yagnikfataniya : 101', on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='officeapp.userprofile'),
        ),
    ]
