# Generated by Django 4.2.4 on 2024-01-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0020_checkinout_user_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckInOut',
        ),
    ]
