# Generated by Django 4.2.4 on 2024-01-18 06:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0021_delete_checkinout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='UserName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='CheckIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(default=datetime.datetime.now)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(default='yagnikfataniya', on_delete=django.db.models.deletion.CASCADE, to='officeapp.userprofile')),
            ],
        ),
    ]
