# Generated by Django 4.2.4 on 2024-01-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0024_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
