# Generated by Django 4.2.4 on 2024-01-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0025_delete_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Policyname', models.CharField(max_length=255)),
                ('Attachments', models.FileField(blank=True, null=True, upload_to='CompanyPolicy/')),
            ],
        ),
    ]
