# Generated by Django 4.2.4 on 2024-01-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0027_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestby', models.CharField(max_length=255)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('days', models.IntegerField()),
                ('leavetype', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Personal Leave', 'Personal Leave'), ('Emergency Leave', 'Emergency Leave')], max_length=255)),
                ('reason', models.TextField()),
            ],
        ),
    ]
