# Generated by Django 4.2.4 on 2024-01-24 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0028_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leavestatus',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('APPROVED', 'APPROVED')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
