# Generated by Django 4.2.4 on 2024-01-25 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0032_remove_leave_id_leave_leaveid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
