# Generated by Django 4.2.4 on 2024-01-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0033_delete_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('leavestatus', models.CharField(choices=[('PENDING', 'PENDING'), ('REJECTED', 'REJECTED'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=100)),
                ('leaveid', models.AutoField(primary_key=True, serialize=False)),
                ('requestby', models.CharField(max_length=255)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('days', models.IntegerField()),
                ('leavetype', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Personal Leave', 'Personal Leave'), ('Emergency Leave', 'Emergency Leave')], max_length=255)),
                ('reason', models.TextField()),
            ],
        ),
    ]
