# Generated by Django 4.2.4 on 2024-01-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0035_alter_task_markasdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Markasdone',
            field=models.BooleanField(default=False),
        ),
    ]
