# Generated by Django 4.2.4 on 2024-01-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0038_room_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
