# Generated by Django 4.2.4 on 2024-01-29 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0039_delete_message_delete_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chetbox',
        ),
    ]
