# Generated by Django 4.2.4 on 2024-01-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0040_delete_chetbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Markasdone',
        ),
        migrations.AddField(
            model_name='task',
            name='TaskStatus',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=10),
        ),
    ]
