# Generated by Django 4.2.4 on 2024-01-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0041_remove_task_markasdone_task_taskstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='TaskStatus',
        ),
        migrations.AddField(
            model_name='task',
            name='Markasdone',
            field=models.BooleanField(default=False),
        ),
    ]
