# Generated by Django 4.2.4 on 2024-01-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0042_remove_task_taskstatus_task_markasdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Markasdone',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=100),
        ),
    ]
