# Generated by Django 4.2.4 on 2024-01-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0043_alter_task_markasdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkio',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
