# Generated by Django 4.2.4 on 2024-02-03 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0046_checkio_defaultdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 11, 13, 37, 140644)),
        ),
    ]
