# Generated by Django 4.2.4 on 2024-02-03 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0047_alter_checkio_defaultdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Announcement', models.CharField(max_length=1000)),
                ('date', models.DateField(default=datetime.date(2024, 2, 3))),
            ],
        ),
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 12, 6, 50, 838438)),
        ),
    ]
