# Generated by Django 4.2.4 on 2024-02-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0050_alter_announcements_date_alter_checkio_defaultdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.DateField(default='2024-02-05'),
        ),
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-02-05 15:10:31.738226'),
        ),
    ]
