# Generated by Django 4.2.4 on 2024-02-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0051_alter_announcements_date_alter_checkio_defaultdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ProjectAbout',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.DateField(default='2024-02-07'),
        ),
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-02-07 12:35:32.457998'),
        ),
    ]
