# Generated by Django 4.2.4 on 2024-02-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0052_task_projectabout_task_remarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='AasignedTo',
        ),
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-02-07 12:40:11.522957'),
        ),
    ]
