# Generated by Django 4.2.4 on 2024-02-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0055_checkio_duration_alter_announcements_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-02-08 11:25:10.504411'),
        ),
    ]
