# Generated by Django 4.2.9 on 2024-02-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0058_alter_checkio_defaultdate_alter_checkio_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='days',
        ),
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.DateField(default='2024-02-09'),
        ),
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-02-09 11:52:41.398113'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startdate',
            field=models.DateField(default='2024-02-09'),
        ),
    ]
