# Generated by Django 4.2.9 on 2024-02-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0059_remove_leave_days_alter_announcements_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-02-09 15:25:55.497096'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskAddedTime',
            field=models.DateField(default='2024-02-09'),
        ),
    ]
