# Generated by Django 4.2.9 on 2024-02-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0060_alter_checkio_defaultdate_alter_task_taskaddedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-02-09 16:46:57.217687'),
        ),
    ]
