# Generated by Django 4.2.9 on 2024-02-21 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0062_remove_userprofile_id_alter_announcements_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=datetime.datetime(2024, 2, 21, 9, 21, 23, 188644, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-02-21 14:51:05.564604'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='UserId',
            field=models.IntegerField(auto_created=True),
        ),
    ]
