# Generated by Django 4.2.9 on 2024-02-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0063_userprofile_id_alter_checkio_defaultdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-02-21 14:52:37.342277'),
        ),
    ]
