# Generated by Django 4.2.9 on 2024-02-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0064_alter_checkio_defaultdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-02-21 14:54:50.110652'),
        ),
    ]
