# Generated by Django 4.2.9 on 2024-02-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0066_alter_checkio_defaultdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='UserId',
        ),
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-02-21 15:00:02.517389'),
        ),
    ]
