# Generated by Django 4.2.9 on 2024-02-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0072_remove_userprofile_id_userprofile_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-02-21 15:23:57.868166'),
        ),
    ]
