# Generated by Django 5.0.2 on 2024-02-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0077_alter_announcements_date_alter_checkio_defaultdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='EmergencyPhoneNo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='RefMo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='RefName',
        ),
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-02-22 15:00:19.917384'),
        ),
    ]
