# Generated by Django 5.0.2 on 2024-03-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0081_alter_announcements_date_alter_checkio_defaultdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-03-02 11:47:16.798761'),
        ),
    ]
