# Generated by Django 5.0.2 on 2024-03-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0082_alter_checkio_defaultdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeusers',
            name='Ip_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.DateField(default='2024-03-04'),
        ),
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-03-04 11:24:21.044597'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startdate',
            field=models.DateField(default='2024-03-04'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskAddedTime',
            field=models.DateField(default='2024-03-04'),
        ),
    ]
