# Generated by Django 5.0.2 on 2024-03-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0083_activeusers_ip_address_alter_announcements_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeusers',
            name='Domain_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-03-04 12:49:17.732509'),
        ),
    ]
