# Generated by Django 5.0.2 on 2024-09-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0084_activeusers_domain_name_alter_checkio_defaultdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskTitle', models.CharField(max_length=255)),
                ('ProjectName', models.CharField(max_length=100)),
                ('TaskType', models.CharField(max_length=100)),
                ('TaskSubtype', models.CharField(max_length=100)),
                ('TaskPriority', models.CharField(max_length=100)),
                ('TaskStart', models.DateTimeField(blank=True, null=True)),
                ('TaskClosed', models.DateTimeField(blank=True, null=True)),
                ('TaskSLA', models.IntegerField()),
                ('RootCase', models.CharField(max_length=1000)),
                ('Attachments', models.FileField(blank=True, null=True, upload_to='Attachments/')),
            ],
        ),
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.DateField(default='2024-09-04'),
        ),
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-09-04 10:10:47.034527'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startdate',
            field=models.DateField(default='2024-09-04'),
        ),
        migrations.AlterField(
            model_name='task',
            name='TaskAddedTime',
            field=models.DateField(default='2024-09-04'),
        ),
    ]
