# Generated by Django 5.0.2 on 2024-09-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0085_taskactions_alter_announcements_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-09-04 10:26:37.561382'),
        ),
        migrations.AlterField(
            model_name='taskactions',
            name='ProjectName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskactions',
            name='TaskPriority',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskactions',
            name='TaskSLA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskactions',
            name='TaskSubtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskactions',
            name='TaskType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
