# Generated by Django 5.0.2 on 2024-09-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0086_alter_checkio_defaultdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskactions',
            name='TaskAddBy',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-09-04 10:28:50.160642'),
        ),
    ]
