# Generated by Django 5.0.2 on 2024-09-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0087_taskactions_taskaddby_alter_checkio_defaultdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskactions',
            name='Markasdone',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='checkio',
            name='defaultdate',
            field=models.DateTimeField(default='2024-09-04 10:48:54.232763'),
        ),
        migrations.AlterField(
            model_name='taskactions',
            name='ProjectName',
            field=models.CharField(blank=True, choices=[('scdp1', 'scdp1'), ('scdp2', 'scdp2'), ('mealplan', 'mealplan'), ('other', 'other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskactions',
            name='TaskPriority',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskactions',
            name='TaskSubtype',
            field=models.CharField(blank=True, choices=[('software', 'software'), ('hardware', 'hardware'), ('other', 'other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskactions',
            name='TaskType',
            field=models.CharField(blank=True, choices=[('service', 'service'), ('development', 'development'), ('incident', 'incident'), ('other', 'other')], max_length=100, null=True),
        ),
    ]
